appName: WeatherAppliance
logLevel: ALL

apiWeatherGov:
  baseUrl: https://api.weather.gov
  authEnvVariable: JNB_APP_WA_APIWEATHERGOV_AUTHKEY
  weatherStation: KBNA
  weatherZone: TNZ027

apiOpenWeather:
  baseUrl: https://api.openweathermap.org
  authEnvVariable: JNB_APP_WA_OPENWEATHERMAP_AUTHKEY
  zipCode: 37076
  countryCode: US

imageParams:
  width: 640
  height: 384
  profile: tiny
