appName: WeatherAppliance
logLevel: ALL

apiWeatherGov:
  baseUrl: https://api.weather.gov
  authEnvVariable: JNB_APP_WA_APIWEATHERGOV_AUTHKEY
  weatherStation: KBNA

imageParams:
  width: 640
  height: 384
  profile: tiny
