appName: "WeatherAppliance"
logLevel: "ALL"

weatherApi:
  baseUrl: "https://api.openweathermap.org"
  authEnvVariable: "JNB_APP_WA_OPENWEATHERMAP_AUTHKEY"
  zipCode: "87101"
  countryCode: "US"
  iconUrl: "http://openweathermap.org/img/wn"
  iconSuffix: "@2x.png"

imageParams:
  width: "640"
  height: "384"
  profile: "tiny"
